---
HSS:
    type: git
    link: https://git.beagleboard.org/beaglev-fire/hart-software-services.git
    branch: ddr-training-speed-up
    board: bvf
gateware:
    type: sources
    unique-design-version: 2.0.2

